node('dedalus-slave') {
    stage('Dedalus Setup') {
        //sh "cd /home/dedalus && bash build_steps/setup.sh"
    }
    stage('Run Example Scripts') {
        sh "cd /home/dedalus && \
            source /home/dedalus/dedalus/bin/activate && \
            python3 simulations/kdv_burgers_test.py"
    }
    stage('Check Example Results') {
        sh "cd /home/dedalus && \
            source /home/dedalus/dedalus/bin/activate && \
            python3 test_functions/test_quantity.py --file=analysis/1d_kdv_analysis.h5 --quantity='<u>'"
    }
}